FROM python:3.13
LABEL authors="mohammad"
LABEL description={{cookiecutter.project_description}}
LABEL version="1.0"
WORKDIR /{{cookiecutter.project_slug}}
COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 8000